import { GoogleGenAI } from '@google/genai';
import { Stance, SourceType } from '@/types';

export interface GeminiImageResult {
  aiProbability: number;
  detectedModel: string;
  reasoning: string[];
  confidence: number;
}

export interface GeminiTextResult {
  score: number;
  confidence: number;
  reasoning: string[];
  references: Array<{
    sourceName: string;
    url: string;
    stance: Stance;
    excerpt: string;
    sourceType: SourceType;
    credibility: number;
    publishedAt: string | null;
  }>;
}

const FALLBACK: GeminiImageResult = {
  aiProbability: 50,
  detectedModel: 'unknown',
  reasoning: ['ไม่สามารถวิเคราะห์ได้ในขณะนี้'],
  confidence: 0,
};

const IMAGE_PROMPT = `You are an expert forensic image analyst. Analyze the provided image and determine if it was generated by AI.

Respond ONLY in valid JSON with this exact structure:
{
  "aiProbability": <number 0-100>,
  "detectedModel": "<Midjourney|DALL-E|Stable Diffusion|unknown>",
  "reasoning": ["<Thai bullet 1>", "<Thai bullet 2>", "<Thai bullet 3>"],
  "confidence": <number 0-100>
}

Analysis criteria:
- Check for unnatural textures, lighting inconsistencies, warped text/hands/fingers
- Look for AI generation artifacts (halos, blending errors, symmetry anomalies)
- Examine background coherence and depth consistency
- All reasoning must be in Thai language
- If unsure, set aiProbability to 50 and confidence to 40`;

const TEXT_PROMPT = `You are a fake news detection expert. Analyze the following claim and assess its credibility.

Respond ONLY in valid JSON with this exact structure:
{
  "score": <number 0-100, where 0=definitely fake, 100=definitely true>,
  "confidence": <number 0-100>,
  "reasoning": ["<bullet 1>", "<bullet 2>", "<bullet 3>"],
  "references": [
    {
      "sourceName": "<source organization name>",
      "stance": "<SUPPORTING|OPPOSING|NEUTRAL>",
      "excerpt": "<short excerpt about this claim>",
      "sourceType": "<TRUSTED_MEDIA|FACT_CHECKER|ACADEMIC|GOV|UNKNOWN>",
      "credibility": <number 0-100>,
      "publishedAt": "<YYYY-MM-DD or null>"
    }
  ]
}

Guidelines:
- score: 0-20 = dangerous misinformation, 21-40 = suspicious, 41-60 = uncertain, 61-80 = likely true, 81-100 = verified
- reasoning: 3-5 bullets in the same language as the input claim
- references: 2-4 relevant real-world sources that would fact-check this claim. Do NOT include url field — real URLs come from Google Search grounding
- If the claim is clearly false/dangerous misinformation, set score <= 30
- If the claim cannot be verified, set score 40-60 and confidence <= 50`;

export async function analyzeTextForFakeNews(query: string): Promise<GeminiTextResult | null> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    console.error('analyzeTextForFakeNews: GEMINI_API_KEY not set');
    return null;
  }

  try {
    const ai = new GoogleGenAI({ apiKey });

    console.log('analyzeTextForFakeNews: sending request to Gemini for query:', query.slice(0, 80));
    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents: `${TEXT_PROMPT}\n\nClaim to analyze: "${query}"`,
      config: {
        tools: [{ googleSearch: {} }],
      },
    });

    const text = (response.text ?? '').trim();
    console.log('analyzeTextForFakeNews: raw Gemini response:', text.slice(0, 200));

    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) {
      console.error('analyzeTextForFakeNews: no JSON in response');
      return null;
    }

    const parsed = JSON.parse(jsonMatch[0]) as Omit<GeminiTextResult, 'references'> & {
      references: Array<Omit<GeminiTextResult['references'][number], 'url'>>;
    };

    const validStances = new Set<string>([Stance.SUPPORTING, Stance.OPPOSING, Stance.NEUTRAL]);
    const validSourceTypes = new Set<string>([
      SourceType.TRUSTED_MEDIA, SourceType.FACT_CHECKER,
      SourceType.ACADEMIC, SourceType.GOV, SourceType.UNKNOWN,
    ]);

    // Real URLs from Google Search grounding — per docs: candidates[0].groundingMetadata.groundingChunks
    const chunks = response.candidates?.[0]?.groundingMetadata?.groundingChunks ?? [];
    const realUrls = chunks
      .filter((c) => c.web?.uri)
      .map((c) => ({ uri: c.web!.uri as string, title: c.web!.title ?? '' }));

    console.log('analyzeTextForFakeNews: grounding URLs found:', realUrls.length);

    const parsedRefs = Array.isArray(parsed.references) ? parsed.references : [];

    // Pair each parsed reference with a real grounding URL
    const mergedRefs = parsedRefs.map((r, i) => ({
      sourceName: String(r.sourceName || realUrls[i]?.title || 'Unknown'),
      url: realUrls[i]?.uri ?? '',
      stance: validStances.has(r.stance) ? (r.stance as Stance) : Stance.NEUTRAL,
      excerpt: String(r.excerpt || ''),
      sourceType: validSourceTypes.has(r.sourceType) ? (r.sourceType as SourceType) : SourceType.UNKNOWN,
      credibility: Math.max(0, Math.min(100, Number(r.credibility) || 50)),
      publishedAt: r.publishedAt ? String(r.publishedAt) : null,
    }));

    // Append leftover grounding results not covered by parsed refs (cap at 4 total)
    for (let i = mergedRefs.length; i < Math.min(realUrls.length, 4); i++) {
      mergedRefs.push({
        sourceName: realUrls[i].title || 'Web Source',
        url: realUrls[i].uri,
        stance: Stance.NEUTRAL,
        excerpt: '',
        sourceType: SourceType.UNKNOWN,
        credibility: 50,
        publishedAt: null,
      });
    }

    return {
      score: Math.max(0, Math.min(100, Number(parsed.score) || 50)),
      confidence: Math.max(0, Math.min(100, Number(parsed.confidence) || 50)),
      reasoning: Array.isArray(parsed.reasoning) ? parsed.reasoning.map(String) : [],
      references: mergedRefs,
    };
  } catch (e) {
    console.error('Gemini text analysis error:', e);
    return null;
  }
}

export async function analyzeImageForAI(
  base64: string,
  mimeType: string,
  caption?: string
): Promise<GeminiImageResult> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) return FALLBACK;

  try {
    const ai = new GoogleGenAI({ apiKey });

    const contents: Array<{ text: string } | { inlineData: { data: string; mimeType: string } }> = [
      { text: IMAGE_PROMPT },
      ...(caption ? [{ text: `Caption/context provided: "${caption}"` }] : []),
      { inlineData: { data: base64, mimeType } },
    ];

    const response = await ai.models.generateContent({
      model: 'gemini-2.5-flash',
      contents,
    });

    const text = (response.text ?? '').trim();
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) return FALLBACK;

    const parsed = JSON.parse(jsonMatch[0]) as GeminiImageResult;
    return {
      aiProbability: Math.max(0, Math.min(100, Number(parsed.aiProbability) || 50)),
      detectedModel: String(parsed.detectedModel || 'unknown'),
      reasoning: Array.isArray(parsed.reasoning) ? parsed.reasoning : [String(parsed.reasoning)],
      confidence: Math.max(0, Math.min(100, Number(parsed.confidence) || 50)),
    };
  } catch (e) {
    console.error('Gemini API error:', e);
    return FALLBACK;
  }
}
