import { GoogleGenerativeAI } from '@google/generative-ai';

export interface GeminiImageResult {
  aiProbability: number;
  detectedModel: string;
  reasoning: string[];
  confidence: number;
}

const FALLBACK: GeminiImageResult = {
  aiProbability: 50,
  detectedModel: 'unknown',
  reasoning: ['ไม่สามารถวิเคราะห์ได้ในขณะนี้'],
  confidence: 0,
};

const PROMPT = `You are an expert forensic image analyst. Analyze the provided image and determine if it was generated by AI.

Respond ONLY in valid JSON with this exact structure:
{
  "aiProbability": <number 0-100>,
  "detectedModel": "<Midjourney|DALL-E|Stable Diffusion|unknown>",
  "reasoning": ["<Thai bullet 1>", "<Thai bullet 2>", "<Thai bullet 3>"],
  "confidence": <number 0-100>
}

Analysis criteria:
- Check for unnatural textures, lighting inconsistencies, warped text/hands/fingers
- Look for AI generation artifacts (halos, blending errors, symmetry anomalies)
- Examine background coherence and depth consistency
- All reasoning must be in Thai language
- If unsure, set aiProbability to 50 and confidence to 40`;

export async function analyzeImageForAI(
  base64: string,
  mimeType: string
): Promise<GeminiImageResult> {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) return FALLBACK;

  try {
    const genAI = new GoogleGenerativeAI(apiKey);
    const model = genAI.getGenerativeModel({ model: 'gemini-3-flash-preview' });

    const result = await model.generateContent([
      PROMPT,
      { inlineData: { data: base64, mimeType } },
    ]);

    const text = result.response.text().trim();
    const jsonMatch = text.match(/\{[\s\S]*\}/);
    if (!jsonMatch) return FALLBACK;

    const parsed = JSON.parse(jsonMatch[0]) as GeminiImageResult;
    return {
      aiProbability: Math.max(0, Math.min(100, Number(parsed.aiProbability) || 50)),
      detectedModel: String(parsed.detectedModel || 'unknown'),
      reasoning: Array.isArray(parsed.reasoning) ? parsed.reasoning : [String(parsed.reasoning)],
      confidence: Math.max(0, Math.min(100, Number(parsed.confidence) || 50)),
    };
  } catch (e) {
    console.error('Gemini API error:', e);
    return FALLBACK;
  }
}
